03/18 10:11:25 PM - app - ERROR : Uh oh, an error has happened! Traceback (most recent call last):
  File "/Users/ErnieParke/Documents/PyCharm/Echo/main.py", line 20, in on_ready
    a /= 0
ZeroDivisionError: division by zero

03/18 10:51:57 PM - app - INFO : The bot has launching!
03/18 11:05:11 PM - app - INFO : The bot is launching!
03/18 11:08:59 PM - app - INFO : The bot is launching!
03/18 11:08:59 PM - app - ERROR : Uh oh, an error has happened! Traceback (most recent call last):
  File "/Users/ErnieParke/Documents/PyCharm/Echo/events.py", line 22, in wrapper
    await func(*args, **kwargs)
  File "/Users/ErnieParke/Documents/PyCharm/Echo/events.py", line 40, in on_ready
    a /= 0
ZeroDivisionError: division by zero

